---
- name: ssh port foreward kubernetes api endpoint
  hosts: localhost
  vars:
    path: ./20220918
    ver: '1'
    namespace: sock-shop
    delay: 200ms
  tasks:
    - name: Run the experiment for carts-db
      block:
        - name: Wait before injecting into carts-db
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject carts-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/carts-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting carts-db_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete carts-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/carts-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/carts-db_experiment_logs.csv 
            mode: '1777'
          vars:
            name: carts-db
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for carts
      block:
        - name: Wait before injecting into carts
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject carts_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/carts_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting carts_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete carts_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/carts_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/carts_experiment_logs.csv 
            mode: '1777'
          vars:
            name: carts
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for catalogue-db
      block:
        - name: Wait before injecting into catalogue-db
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject catalogue-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/catalogue-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting catalogue-db_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete catalogue-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/catalogue-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/catalogue-db_experiment_logs.csv 
            mode: '1777'
          vars:
            name: catalogue-db
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for catalogue
      block:
        - name: Wait before injecting into catalogue
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject catalogue_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/catalogue_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting catalogue_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete catalogue_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/catalogue_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/catalogue_experiment_logs.csv 
            mode: '1777'
          vars:
            name: catalogue
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for front-end
      block:
        - name: Wait before injecting into front-end
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject front-end_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/front-end_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting front-end_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete front-end_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/front-end_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/front-end_experiment_logs.csv 
            mode: '1777'
          vars:
            name: front-end
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for orders-db
      block:
        - name: Wait before injecting into orders-db
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject orders-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/orders-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting orders-db_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete orders-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/orders-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/orders-db_experiment_logs.csv 
            mode: '1777'
          vars:
            name: orders-db
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for orders
      block:
        - name: Wait before injecting into orders
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject orders_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/orders_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting orders_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete orders_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/orders_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/orders_experiment_logs.csv 
            mode: '1777'
          vars:
            name: orders
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for payment
      block:
        - name: Wait before injecting into payment
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject payment_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/payment_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting payment_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete payment_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/payment_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/payment_experiment_logs.csv 
            mode: '1777'
          vars:
            name: payment
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for queue-master
      block:
        - name: Wait before injecting into queue-master
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject queue-master_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/queue-master_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting queue-master_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete queue-master_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/queue-master_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/queue-master_experiment_logs.csv 
            mode: '1777'
          vars:
            name: queue-master
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for rabbitmq
      block:
        - name: Wait before injecting into rabbitmq
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject rabbitmq_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/rabbitmq_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting rabbitmq_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete rabbitmq_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/rabbitmq_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/rabbitmq_experiment_logs.csv 
            mode: '1777'
          vars:
            name: rabbitmq
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for session-db
      block:
        - name: Wait before injecting into session-db
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject session-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/session-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting session-db_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete session-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/session-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/session-db_experiment_logs.csv 
            mode: '1777'
          vars:
            name: session-db
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for shipping
      block:
        - name: Wait before injecting into shipping
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject shipping_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/shipping_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting shipping_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete shipping_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/shipping_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/shipping_experiment_logs.csv 
            mode: '1777'
          vars:
            name: shipping
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for user-db
      block:
        - name: Wait before injecting into user-db
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject user-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/user-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting user-db_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete user-db_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/user-db_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/user-db_experiment_logs.csv 
            mode: '1777'
          vars:
            name: user-db
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

    - name: Run the experiment for user
      block:
        - name: Wait before injecting into user
          ansible.builtin.wait_for:
            timeout: 120

        - name: Inject user_chaos_experiment.yaml
          ansible.builtin.command: "kubectl apply -f ./manifests/user_chaos_experiment.yaml"
          changed_when: true
          register: experiment_start

        - name: Wait before deleting user_chaos_experiment.yaml
          ansible.builtin.wait_for:
            timeout: 60

        - name: Delete user_chaos_experiment.yaml
          ansible.builtin.command: "kubectl delete -f ./manifests/user_chaos_experiment.yaml"
          changed_when: true
          register: experiment_end

        - name: Record the experiment
          ansible.builtin.template:
            src: ./logs/experiment_logs.csv.j2
            dest: ./logs/user_experiment_logs.csv 
            mode: '1777'
          vars:
            name: user
            start_time: "{{ experiment_start.end }}"
            end_time: "{{ experiment_end.end }}"

        - name: Wait before starting next experiement
          ansible.builtin.wait_for:
            timeout: 60

