---
path: ./fanout
ver: foc10
namespace: foc10
description: "Fanout topology of width 10"
delay: 30ms
duration: 60s
direction: both #to, from, or both
rca_filename: run_microrca.py
rca_dir: ./rca/
alpha: 0.55
ad_threshold: 0.05
alpha_threshold:
  - { alpha: 0.3, threshold: 0.07}
  - { alpha: 0.7, threshold: 0.03}
  - { alpha: 0.5, threshold: 0.05}
include_db: False
