apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: user-db-delay-v4-t3
  namespace: chaos-testing
spec:
  action: delay 
  mode: one 
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      'name': user-db
  delay:
    latency: 30ms
  duration: 60s
