# vim: set filetype=yaml.ansible :
---
- name: Generate batch chaos experiment
  hosts: localhost
  vars:
    name: chain-fanout-s-v2
    chains:
      # - chc5
      # - chc10
      # - chc15
      - chc5s
      - chc10s
      - chc15s
    fanouts:
      # - foc5
      # - foc10
      # - foc15
      - foc5s
      - foc10s
      - foc15s
    path:
      generate_experiment: "{{ playbook_dir }}"
      k8s_deploy_base: "/Users/hirokihanada/code/src/github.com/hanapedia/microservices-topologies/generated"
  tasks:
    - name: Make directory for bach experiments
      ansible.builtin.file:
        path: ./batch_experiments/{{ name }}
        state: directory
        mode: '1777'

    - name: Generate batch experiment
      ansible.builtin.template:
        src: ./templates/batch_experiment.yaml.j2
        dest: "./batch_experiments/{{ name }}/batch_experiment.yaml"
        mode: '1777'

    - name: Generate batch experiment details
      ansible.builtin.template:
        src: "./templates/batch_experiment_details.md.j2"
        dest: ./batch_experiments/{{ name }}/README.md
        mode: '1777'
