apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: orders-delay-v2
  namespace: sock-shop
spec:
  hosts:
  - orders.sock-shop.svc.cluster.local
  http:
  - fault:
      delay:
        percentage:
          value: 100
        fixedDelay: 200ms
    route:
    - destination:
        host: orders.sock-shop.svc.cluster.local
