apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: user-db-delay-v2
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      'name': user-db
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: 60s
