apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-with-duration
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      'name': 'user'
  stressors:
    memory:
      workers: 4
      size: '1024MB'
  duration: 60s
