kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-cluster-manager-xmiao
automountServiceAccountToken: true

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-manager-xmiao
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-manager-xmiao
subjects:
- kind: ServiceAccount
  name: account-cluster-manager-xmiao
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-cluster-manager-xmiao
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: account-cluster-manager-xmiao-secret
  annotations:
    kubernetes.io/service-account.name: account-cluster-manager-xmiao
type: kubernetes.io/service-account-token
