apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: front-end-delay-v4-t2
  namespace: chaos-testing
spec:
  action: delay 
  mode: one 
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      'name': front-end
  delay:
    latency: 30ms
  duration: 60s
