# vim: set filetype=yaml.ansible :
---
- name: ssh port foreward kubernetes api endpoint
  hosts: localhost
  tasks:
    - name: Generate kubernetes manifests
      block:
        - name: Get the list of service names and save it to variable
          ansible.builtin.shell: "set -o pipefail && kubectl get svc -n sock-shop | awk 'NR>1{ print $1 }'"
          changed_when: true
          register: services

        - name: Ensure that destination directory exists
          ansible.builtin.file:
            path: "{{ path }}"
            state: directory
            mode: '1777'

        - name: Ensure that versioned directory exists
          ansible.builtin.file:
            path: "{{ path }}/{{ ver }}"
            state: directory
            mode: '1777'

        - name: Ensure that manifests directory exists
          ansible.builtin.file:
            path: "{{ path }}/{{ ver }}/manifests"
            state: directory
            mode: '1777'

        - name: Generate chaos experiments
          ansible.builtin.template:
            src: ./templates/chaos_experiment_manifest.yaml.j2
            dest: "{{ path }}/{{ ver }}/manifests/{{ item }}_chaos_experiment.yaml"
            mode: '1777'
          vars:
            service: "{{ item }}"
          with_items: "{{ services.stdout_lines }}"

    - name: Generate ansible yaml for experiment
      block:
        - name: Prepare logging directory
          ansible.builtin.file:
            path: "{{ path }}/{{ ver }}/logs"
            state: directory
            mode: '1777'

        - name: Prepare rca directory
          ansible.builtin.file:
            path: "{{ path }}/{{ ver }}/{{ rca_dir }}"
            state: directory
            mode: '1777'

        - name: Copy logging template to logs directory
          ansible.builtin.copy:
            src: ./templates/experiment_logs.csv.j2
            dest: "{{ path }}/{{ ver }}/logs/experiment_logs.csv.j2"
            mode: '1777'

        - name: Retreive the filenames for all of the manifests
          ansible.builtin.command: "ls {{ path }}/{{ ver }}/manifests"
          changed_when: true
          register: files

        - name: Generate experiment script playbook
          ansible.builtin.template:
            src: ./templates/experiment_script.yaml.j2
            dest: "{{ path }}/{{ ver }}/experiment_script.yaml"
            mode: '1777'
          vars:
            manifests: "{{ files.stdout_lines }}"

        - name: Copy python script to run rca
          ansible.builtin.copy:
            src: "../rca/{{ rca_filename }}"
            dest: "{{ path }}/{{ ver }}/rca.py"
            mode: '1777'
        # - name: debug
        #   ansible.builtin.debug:
        #     msg: "{{ manifests }}"
