apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: carts-db-delay-v4-t5
  namespace: chaos-testing
spec:
  action: delay 
  mode: one 
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      'name': carts-db
  delay:
    latency: 30ms
  duration: 60s
